# Generated by Django 3.1.1 on 2020-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergen_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('scora_nova_group', models.IntegerField(null=True)),
                ('nutri_score_grad', models.CharField(max_length=1, null=True)),
                ('food_url', models.TextField(null=True)),
                ('alergen_list', models.ManyToManyField(blank=True, related_name='food_list', to='search_app.Alergen')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('diet_type', models.CharField(max_length=200, null=True)),
                ('alergy', models.ManyToManyField(blank=True, related_name='users', to='search_app.Alergen')),
                ('search_food', models.ManyToManyField(blank=True, related_name='users', to='search_app.Food_list')),
            ],
        ),
    ]
