# Generated by Django 3.1.1 on 2020-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0002_myusers_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='alergy',
            field=models.ManyToManyField(null=True, to='database_handler_app.Allergen'),
        ),
    ]
