# Generated by Django 3.1.1 on 2020-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0002_auto_20201006_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='diet_type',
        ),
        migrations.AddField(
            model_name='myusers',
            name='diet_type',
            field=models.ManyToManyField(to='database_handler_app.Diet'),
        ),
    ]
