# Generated by Django 3.1.1 on 2020-10-06 19:27

from django.db import migrations


def combine_diet(apps, schema_editor):
    Diet = apps.get_model('database_handler_app', 'Diet')
    diet_list = ['omnivore', 'végétarien', 'végétalien', 'carnivore', 'anthropophage', 'pesco-végétarien', 'crudivore']
    for diet_type in diet_list:
        Diet.objects.create(diet_name=diet_type)


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0003_auto_20201006_2117'),
    ]

    operations = [
        # migrations.RunPython(combine_diet),
    ]
