# Generated by Django 3.1.1 on 2020-10-06 20:23

from django.db import migrations


def combine_alergen(apps, schema_editor):
    Alergen = apps.get_model('database_handler_app', 'Alergen')
    alergen_list = ['oeuf', 'crustacés', 'poisson', 'lait', 'blé', 'légumineuses', 'banane', 'avocat', 'kiwi', 'moules',
                    'pommes de terre', 'tournesol', 'boeuf', 'arachide', 'mangue']
    for alergen_type in alergen_list:
        Alergen.objects.create(alergen_name=alergen_type)


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0005_auto_20201006_2148'),
    ]

    operations = [
        # migrations.RunPython(combine_alergen),
    ]
