# Generated by Django 3.1.1 on 2020-11-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0006_auto_20201006_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='alergen_name',
            new_name='allergen_name',
        ),
        migrations.RenameField(
            model_name='foodlist',
            old_name='alergen_list',
            new_name='allergen_list',
        ),
    ]
