# Generated by Django 3.1.1 on 2020-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0008_auto_20201207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='image_profile',
            field=models.ImageField(blank=True, default='/media/elephant.jpeg', null=True, upload_to='profile_image/'),
        ),
    ]
