# Generated by Django 3.1.1 on 2020-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler_app', '0009_auto_20201207_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='image_profile',
            field=models.ImageField(blank=True, default='media/elephant.jpeg', null=True, upload_to='media/profile_image/'),
        ),
    ]
